version: 2.1

jobs:
  TEST:
    docker:
      # specify the version you desire here
      - image: flycheck/emacs-cask:26.2
    working_directory: ~/repo
    environment:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Cask" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cask install
      - save_cache:
          paths:
            - ~/.cask
          key: v1-dependencies-{{ checksum "Cask" }}

      # run tests!
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - TEST
